name: myservice
image:
  registry: x.y.z
  name: myServiceImage
  tag: 1.2.3
  dockerfile:
    path: /abc
    dockerfilePath: /Dockerfile
    args:
       key1: value1

startCommand: "a,bc,def"
replicas: 2
memory: 123Mi-456Mi
cpu: 123m-456m

volumes:
  - name: vol-name
    path: /volume/mount/path
    size: 1Gi
    storageClass: storageClass

external: true
ports:
  - port: 8080/tcp
    healthCheck:
      httpPath: /sample
  - port : 8081

propsVolumePath: /abc/def/props.txt
props:
    key1: value1
    key2: value2

secretsVolumePath: /abc/def/secrets.txt
secrets:
  - skey1
  - skey2

