#!/bin/bash
set -euo pipefail
HYS_VERSION="0.9.4.1.183"
HYS_JAR_BIN="hyscale-${HYS_VERSION}.jar"
HYS_CONF_DIR="$HOME/.hyscale" 

check_java_version(){
  java --version > /dev/null 2>&1
  if [ $? != 0  ]
  then
    echo "Java is not installed"
    exit 1
  elif [ $(java  -version 2>&1 | awk -F '"' '/version/ {print $2}'| awk -F '.' '{print $1}') -lt 11 ]
  then
     echo "JDK version 11 and above is required but found lesser version"
     exit 1
  fi
}

download_hyscale_jar(){
  #Check if the $HYS_CONF_DIR dir exists, else create.
  if [ ! -d $HYS_CONF_DIR  ]
  then
     mkdir -p $HYS_CONF_DIR
  fi
  #Delete the old existing hyscale-*.jar files in $HYS_CONF_DIR and download the latest jar
  if [ ! -f ${HYS_CONF_DIR}/${HYS_JAR_BIN} ]
  then
    rm -rf ${HYS_CONF_DIR}/hyscale-*.jar
    if [[  ! `wget --server-response https://github.com/hyscale/hyscale/releases/latest/download/hyscale.jar -O ${HYS_JAR_BIN}  2>&1 | grep 'HTTP/1.1 200 OK'` ]];
    then
         echo "Download failed"
	 exit 1
    fi
    mv ${HYS_JAR_BIN} ${HYS_CONF_DIR}
  fi
}

check_java_version
download_hyscale_jar

java -Djdk.tls.client.protocols=TLSv1.2 -Xms216m -Xmx512m -jar ${HYS_CONF_DIR}/${HYS_JAR_BIN} $@
