FROM {{ STACK_IMAGE }}
{{#artifacts.isNotEmpty}}
{{#artifacts}}
COPY {{source}} {{destination}}
{{/artifacts}}
{{/artifacts.isNotEmpty}}
{{#CONFIGURE_SCRIPT_FILE}}
ADD {{CONFIGURE_SCRIPT_FILE}} {{SCRIPT_DIR}} 
{{/CONFIGURE_SCRIPT_FILE}}
{{#RUN_SCRIPT_FILE}}
ADD {{RUN_SCRIPT_FILE}} {{SCRIPT_DIR}}
{{/RUN_SCRIPT_FILE}}
{{#PERMISSION_COMMAND}}
RUN {{{PERMISSION_COMMAND}}} {{SCRIPT_DIR}}
{{/PERMISSION_COMMAND}}
{{#CONFIGURE_SCRIPT_FILE}}
RUN {{SCRIPT_DIR}}{{CONFIGURE_SCRIPT_FILE}}
{{/CONFIGURE_SCRIPT_FILE}}
{{#RUN_SCRIPT_FILE}}
ENTRYPOINT ["{{SHELL_START}}","{{SCRIPT_DIR}}{{RUN_SCRIPT_FILE}}"]
{{/RUN_SCRIPT_FILE}}
