# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
        prefix: client

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
          echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          #echo $BUILD_NUMBER
          sed -i "s|@@BUILD_NUMBER@@|$Hyscale_Docker_Image_Tag.$BUILD_NUMBER|g" scripts/*
          sed -i "s|@@HYSCALE_BUILD_VERSION@@|$Hyscale_Docker_Image_Tag.$BUILD_NUMBER|g" scripts/*
          cat scripts/hyscale
          #docker push registry.hyscale.io/hyscale/hyscale:test.$BUILD_NUMBER
          #docker rmi -f registry.hyscale.io/hyscale/hyscale:test.$BUILD_NUMBER

    - uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: hyscale/hyscale
        tag: test
        registry: registry.hyscale.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        #FILE: scripts/hyscale
        AWS_S3_BUCKET: 'wavemaker-downloading-testing'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'scripts'      # optional: defaults to entire repository
        DEST_DIR: '/'
